### ISSUE TITLE
Invalid username

### ISSUE THREAD

**Issue by jvdoorn** [simplyGits/magisterjs-authcode#2]
`magister.js` started throwing an "invalid username" error, which I guess means that the authentication token expired again. Someone once told me to just create a PR when it happens but I have no way to request the token. Probably @lieuwex needs to take a look at this.

**Comment by lieuwex** [comment]
Can you check again (figuring you're fetching the authcode using http)? The update script still had some issues, it has updated the npm package but now the git version. I will try to fix the script again with _rough_ patch, but whatever. I'm not really sure (have no access to magister whatsoever, since I'm in uni)

**Comment by lieuwex** [comment]
I've updated my script again (had the wrong env vars), so I hope git should actually work now.

**Comment by jvdoorn** [comment]
It works, though I request the token through an HTTP request and not NPM, so I don't know if NPM works.
